### ISSUE TITLE
build using hugo

### ISSUE THREAD

**Issue by c7h** [nerdkiez/nerdkiez.github.io#1]
We could use ~jekyll~ hugo to generate a static html page including neat view of all recipes in https://github.com/nerdkiez/recipes

~https://help.github.com/en/articles/using-jekyll-as-a-static-site-generator-with-github-pages~

https://gohugo.io/hosting-and-deployment/hosting-on-github/

EDIT: @ChrisWeissmann prefers hugo over jekyll.

Acceptance Criteria:

Automated builds and deployments on travisci or similar.

**Comment by ChrisWeissmann** [comment]
Fine fine, we can go with Jakyll
